//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganizationProject_ADO_WPF.WCF_ADOReference {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TableNames", Namespace="http://schemas.datacontract.org/2004/07/OrganizationProject_ADO_Library.Enums")]
    public enum TableNames : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Departments = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Employees = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF_ADOReference.IDBAccess")]
    public interface IDBAccess {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBAccess/GetData", ReplyAction="http://tempuri.org/IDBAccess/GetDataResponse")]
        void GetData(OrganizationProject_ADO_WPF.WCF_ADOReference.TableNames name, System.Data.DataTable table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBAccess/GetData", ReplyAction="http://tempuri.org/IDBAccess/GetDataResponse")]
        System.Threading.Tasks.Task GetDataAsync(OrganizationProject_ADO_WPF.WCF_ADOReference.TableNames name, System.Data.DataTable table);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDBAccessChannel : OrganizationProject_ADO_WPF.WCF_ADOReference.IDBAccess, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DBAccessClient : System.ServiceModel.ClientBase<OrganizationProject_ADO_WPF.WCF_ADOReference.IDBAccess>, OrganizationProject_ADO_WPF.WCF_ADOReference.IDBAccess {
        
        public DBAccessClient() {
        }
        
        public DBAccessClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBAccessClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBAccessClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBAccessClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GetData(OrganizationProject_ADO_WPF.WCF_ADOReference.TableNames name, System.Data.DataTable table) {
            base.Channel.GetData(name, table);
        }
        
        public System.Threading.Tasks.Task GetDataAsync(OrganizationProject_ADO_WPF.WCF_ADOReference.TableNames name, System.Data.DataTable table) {
            return base.Channel.GetDataAsync(name, table);
        }
    }
}
